OBJS	= Environment.o Error.o Expr.o Interpreter.o Lexer.o Parser.o Stmt.o main.o
SOURCE	= Environment.cpp Error.cpp Expr.cpp Interpreter.cpp Lexer.cpp Parser.cpp Stmt.cpp main.cpp
HEADER	= Environment.hpp Error.hpp Expr.hpp Interpreter.hpp Lexer.hpp Parser.hpp Stmt.hpp Token.hpp TokenType.hpp
OUT	= mpas.out
CC	 = g++
FLAGS	 = -g -c -Wall
LFLAGS	 = 

all: $(OBJS)
	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)

Environment.o: Environment.cpp
	$(CC) $(FLAGS) Environment.cpp -std=c++17

Error.o: Error.cpp
	$(CC) $(FLAGS) Error.cpp -std=c++17

Expr.o: Expr.cpp
	$(CC) $(FLAGS) Expr.cpp -std=c++17

Interpreter.o: Interpreter.cpp
	$(CC) $(FLAGS) Interpreter.cpp -std=c++17

Lexer.o: Lexer.cpp
	$(CC) $(FLAGS) Lexer.cpp -std=c++17

Parser.o: Parser.cpp
	$(CC) $(FLAGS) Parser.cpp -std=c++17

Stmt.o: Stmt.cpp
	$(CC) $(FLAGS) Stmt.cpp -std=c++17

main.o: main.cpp
	$(CC) $(FLAGS) main.cpp -std=c++17


clean:
	rm -f $(OBJS) $(OUT)
